<?php

add_action('acf/init', function () {
    if (!function_exists('acf_add_options_page')) {
        return;
    }

    acf_add_options_page(array(
        'page_title' => 'Header Main',
        'menu_slug' => 'header_main',
        'redirect' => false,
    ));
});

add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_651b29efc2e1d',
        'title' => 'Megamenu',
        'fields' => array(
            array(
                'key' => 'field_651b44c8f2cd5',
                'label' => 'Header Logo',
                'name' => 'header_logo',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_651b44eef2cd6',
                'label' => 'CTA Button',
                'name' => 'cta_button',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_651b2d08531e0',
                'label' => 'Nav Items',
                'name' => 'nav_item',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Nav Item',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_651b2d32531e1',
                        'label' => '',
                        'name' => 'link',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b29f0160b7',
                        'label' => 'Include Megamenu',
                        'name' => 'include_megamenu',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'If Yes, link URL will be ignored.',
                        'default_value' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b2a61160b8',
                        'label' => 'Left Column',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_651b29f0160b7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b2afd160bb',
                        'label' => '',
                        'name' => 'column_1',
                        'aria-label' => '',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_651b29f0160b7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layouts' => array(
                            'layout_651b2b12ea207' => array(
                                'key' => 'layout_651b2b12ea207',
                                'name' => 'heading_subtitle',
                                'label' => 'Heading (Subtitle)',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_651b2b6d160be',
                                        'label' => '',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => 'Text',
                                        'append' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_651b2b54160bc' => array(
                                'key' => 'layout_651b2b54160bc',
                                'name' => 'megamenu_item',
                                'label' => 'Megamenu Item',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_651b2b99160bf',
                                        'label' => 'Icon',
                                        'name' => 'icon',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'thumbnail',
                                    ),
                                    array(
                                        'key' => 'field_651b2ba6160c0',
                                        'label' => '',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '70',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                    array(
                                        'key' => 'field_651b2bac160c1',
                                        'label' => 'Description',
                                        'name' => 'description',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => 3,
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                    ),
                                    array(
                                        'key' => 'field_651b2bb4160c2',
                                        'label' => 'Other Links',
                                        'name' => 'other_links',
                                        'aria-label' => '',
                                        'type' => 'group',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b2bc9160c3',
                                                'label' => 'Title',
                                                'name' => 'title',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                            ),
                                            array(
                                                'key' => 'field_651b2bd1160c4',
                                                'label' => 'Links',
                                                'name' => 'links',
                                                'aria-label' => '',
                                                'type' => 'repeater',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'layout' => 'table',
                                                'pagination' => 0,
                                                'min' => 0,
                                                'max' => 0,
                                                'collapsed' => '',
                                                'button_label' => 'Add Link',
                                                'rows_per_page' => 20,
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_651b2bdc160c5',
                                                        'label' => 'Link',
                                                        'name' => 'link',
                                                        'aria-label' => '',
                                                        'type' => 'link',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'parent_repeater' => 'field_651b2bd1160c4',
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                        'button_label' => 'Add Item to Left Column',
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b3cd431160',
                        'label' => 'Middle Column',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_651b29f0160b7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b400736359',
                        'label' => '',
                        'name' => 'column_2',
                        'aria-label' => '',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_651b29f0160b7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layouts' => array(
                            'layout_651b2b12ea207' => array(
                                'key' => 'layout_651b2b12ea207',
                                'name' => 'heading_subtitle',
                                'label' => 'Heading (Subtitle)',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_651b40073635a',
                                        'label' => '',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => 'Text',
                                        'append' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_651b2b54160bc' => array(
                                'key' => 'layout_651b2b54160bc',
                                'name' => 'megamenu_item',
                                'label' => 'Megamenu Item',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_651b40073635b',
                                        'label' => 'Icon',
                                        'name' => 'icon',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'thumbnail',
                                    ),
                                    array(
                                        'key' => 'field_651b40073635c',
                                        'label' => '',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '70',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                    array(
                                        'key' => 'field_651b40073635d',
                                        'label' => 'Description',
                                        'name' => 'description',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => 3,
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                    ),
                                    array(
                                        'key' => 'field_651b40073635e',
                                        'label' => 'Other Links',
                                        'name' => 'other_links',
                                        'aria-label' => '',
                                        'type' => 'group',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b40073635f',
                                                'label' => 'Title',
                                                'name' => 'title',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                            ),
                                            array(
                                                'key' => 'field_651b400736360',
                                                'label' => 'Links',
                                                'name' => 'links',
                                                'aria-label' => '',
                                                'type' => 'repeater',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'layout' => 'table',
                                                'pagination' => 0,
                                                'min' => 0,
                                                'max' => 0,
                                                'collapsed' => '',
                                                'button_label' => 'Add Link',
                                                'rows_per_page' => 20,
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_651b400736361',
                                                        'label' => 'Link',
                                                        'name' => 'link',
                                                        'aria-label' => '',
                                                        'type' => 'link',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'parent_repeater' => 'field_651b400736360',
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                        'button_label' => 'Add Item to Middle Column',
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b3d283116a',
                        'label' => 'Right Column',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_651b29f0160b7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                    array(
                        'key' => 'field_651b43003396e',
                        'label' => '',
                        'name' => 'column_3_data',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_651b43193396f',
                                'label' => 'Image',
                                'name' => 'image',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => 'Will be placed in right bottom corner of the column.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_651b434b33970',
                                'label' => 'Column Background Color',
                                'name' => 'column_background_color',
                                'aria-label' => '',
                                'type' => 'color_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#f9f8f8',
                                'enable_opacity' => 0,
                                'return_format' => 'string',
                            ),
                            array(
                                'key' => 'field_651b413ef407c',
                                'label' => '',
                                'name' => 'column_3',
                                'aria-label' => '',
                                'type' => 'flexible_content',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_651b29f0160b7',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layouts' => array(
                                    'layout_651b2b12ea207' => array(
                                        'key' => 'layout_651b2b12ea207',
                                        'name' => 'heading_subtitle',
                                        'label' => 'Heading (Subtitle)',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b413ef407d',
                                                'label' => '',
                                                'name' => 'text',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => 'Text',
                                                'append' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_651b419bf4085' => array(
                                        'key' => 'layout_651b419bf4085',
                                        'name' => 'heading_title',
                                        'label' => 'Heading (Title)',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b419bf4086',
                                                'label' => '',
                                                'name' => 'text',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => 'Text',
                                                'append' => '',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_651b41b9f4088' => array(
                                        'key' => 'layout_651b41b9f4088',
                                        'name' => 'text_block',
                                        'label' => 'Text Block',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b41d1f408a',
                                                'label' => '',
                                                'name' => 'text',
                                                'aria-label' => '',
                                                'type' => 'wysiwyg',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'tabs' => 'visual',
                                                'toolbar' => 'basic',
                                                'media_upload' => 0,
                                                'delay' => 0,
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_651b4258dd7c0' => array(
                                        'key' => 'layout_651b4258dd7c0',
                                        'name' => 'link_button',
                                        'label' => 'Link (Button)',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b4263dd7c2',
                                                'label' => 'Link',
                                                'name' => 'link',
                                                'aria-label' => '',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '50',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                            ),
                                            array(
                                                'key' => 'field_651b429add7c3',
                                                'label' => 'Add to Margin Top',
                                                'name' => 'add_to_margin_top',
                                                'aria-label' => '',
                                                'type' => 'number',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '50',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => 36,
                                                'min' => '',
                                                'max' => '',
                                                'placeholder' => '',
                                                'step' => '',
                                                'prepend' => '',
                                                'append' => 'px',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_651b650d99a5a' => array(
                                        'key' => 'layout_651b650d99a5a',
                                        'name' => 'article',
                                        'label' => 'Article',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b655499a5c',
                                                'label' => 'Size',
                                                'name' => 'size',
                                                'aria-label' => '',
                                                'type' => 'select',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'choices' => array(
                                                    'small' => 'small',
                                                    'medium' => 'medium',
                                                ),
                                                'default_value' => false,
                                                'return_format' => 'value',
                                                'multiple' => 0,
                                                'allow_null' => 0,
                                                'ui' => 0,
                                                'ajax' => 0,
                                                'placeholder' => '',
                                            ),
                                            array(
                                                'key' => 'field_651b657299a5d',
                                                'label' => 'Image',
                                                'name' => 'image',
                                                'aria-label' => '',
                                                'type' => 'image',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                                'library' => 'all',
                                                'min_width' => '',
                                                'min_height' => '',
                                                'min_size' => '',
                                                'max_width' => '',
                                                'max_height' => '',
                                                'max_size' => '',
                                                'mime_types' => '',
                                                'preview_size' => 'medium',
                                            ),
                                            array(
                                                'key' => 'field_651b658899a5e',
                                                'label' => 'Link Tag',
                                                'name' => 'link_tag',
                                                'aria-label' => '',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                            ),
                                            array(
                                                'key' => 'field_651b659a99a5f',
                                                'label' => 'Link',
                                                'name' => 'link',
                                                'aria-label' => '',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    'layout_651b65b899a60' => array(
                                        'key' => 'layout_651b65b899a60',
                                        'name' => 'social_links_block',
                                        'label' => 'Social Links Block',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_651b65c399a62',
                                                'label' => 'Social Links',
                                                'name' => 'social_links',
                                                'aria-label' => '',
                                                'type' => 'repeater',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'layout' => 'table',
                                                'min' => 0,
                                                'max' => 0,
                                                'collapsed' => '',
                                                'button_label' => 'Add Row',
                                                'rows_per_page' => 20,
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_651b65de99a63',
                                                        'label' => 'Type',
                                                        'name' => 'type',
                                                        'aria-label' => '',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '50',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'linkedin' => 'Linkedin',
                                                            'mail' => 'Mail',
                                                        ),
                                                        'default_value' => false,
                                                        'return_format' => 'value',
                                                        'multiple' => 0,
                                                        'allow_null' => 0,
                                                        'ui' => 1,
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                        'parent_repeater' => 'field_651b65c399a62',
                                                    ),
                                                    array(
                                                        'key' => 'field_651b661399a64',
                                                        'label' => 'Link',
                                                        'name' => 'link',
                                                        'aria-label' => '',
                                                        'type' => 'link',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '50',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'parent_repeater' => 'field_651b65c399a62',
                                                    ),
                                                ),
                                            ),
                                        ),
                                        'min' => '',
                                        'max' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                                'button_label' => 'Add Item to Middle Column',
                            ),
                        ),
                        'parent_repeater' => 'field_651b2d08531e0',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'header_main',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'discussion',
            4 => 'comments',
            5 => 'revisions',
            6 => 'slug',
            7 => 'author',
            8 => 'format',
            9 => 'page_attributes',
            10 => 'featured_image',
            11 => 'categories',
            12 => 'tags',
            13 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
